zh-Hans.lproj/Panel.strings

merge some fix from https://github.com/typora/Typora-i18n/pull/1

Fixed some Chinese translation

---

ko-KR.lproj/Front.strings
ko-KR.lproj/Menu.strings
ko-KR.lproj/Panel.strings

Hi! I translated app to Korean. Please let me know if something is wrong. Thanks.

Add Korean language

---

ko-KR.lproj/Front.strings
ko-KR.lproj/Menu-electron.strings
ko-KR.lproj/Menu.strings
ko-KR.lproj/Panel.strings

Improve Korean translations

---

Base.lproj/Menu.strings
Base.lproj/Panel.strings
ko-KR.lproj/Menu.strings
ko-KR.lproj/Panel.strings
pl-PL.lproj/Menu.strings
pl-PL.lproj/Panel.strings
zh-Hans.lproj/Menu.strings
zh-Hans.lproj/Panel.strings
zh-Hant.lproj/Menu.strings
zh-Hant.lproj/Panel.strings

This fixes some typos in the translation files as reported in #19.

Fix: typos

---

it-IT.lproj/Front.strings
it-IT.lproj/Menu.strings
it-IT.lproj/Panel.strings

Translated files:
- Front.strings
- Menu.strings
- Panel.strings
Reference: #14

Add: Italian translation [it-IT]

---

ru-RU.lproj/Front.strings
ru-RU.lproj/Menu.strings
ru-RU.lproj/Panel.strings

First commit. It is required to test ;)

Russian translation

---

ja-JP.lproj/Front.strings
ja-JP.lproj/Menu.strings
ja-JP.lproj/Panel.strings

I have completed Japanese translation.

Japanese Translation Completed

---

pt-BR.lproj/Front.strings
pt-BR.lproj/Menu.strings
pt-BR.lproj/Panel.strings

Add pt-BR translation

---

el-GR.lproj/Front.strings
el-GR.lproj/Menu.strings
el-GR.lproj/Panel.strings

I finished Greek translations. Feel free to tell me if anything needs improvement/change.

Greek translations

---

ko-KR.lproj/Menu.strings

Update Menu.strings (ko-KR)

---

fr-FR.lproj/Panel.strings

Save|Discard|Cancel is currently Enregistrer|Annuler|Annuler, fixed that :globe_with_meridians:

discard != cancel

---

cs-CZ.lproj/Panel.strings

Update cs Panel.strings

---

cs-CZ.lproj/Menu.strings

Update cs Menu.strings

---

cs-CZ.lproj/Front.strings

Update cs Front.strings

---

ko-KR.lproj/Front.strings
ko-KR.lproj/Menu.strings
ko-KR.lproj/Panel.strings

Added Korean Translate and modified some contents.

Added Korean Translate.

---

ko-KR.lproj/Panel.strings

Update Panel.strings [ko_KR]

---

zh-Hans.lproj/Panel.strings

Typo 对其 -> 对齐

---

sv-SE.lproj/Front.strings
sv-SE.lproj/Menu.strings
sv-SE.lproj/Panel.strings

I have translated almost all strings but am still unsure about a few and could use some help putting them into context (see comment section below).

Added Swedish Translations

---

es-ES.lproj/Front.strings
es-ES.lproj/Menu.strings
es-ES.lproj/Panel.strings

* Fixed some mistakes
* No accents in pronouns 
* Closes #68 
* Fixes PR #80

Fixed spanish language

---

zh-Hans.lproj/Front.strings
zh-Hans.lproj/Menu.strings
zh-Hans.lproj/Panel.strings

Update zh-Hans.lproj (3 files)
By Mornwind

Update zh-Hans.lproj (3 files)

---

gl-ES.lproj/Front.strings
gl-ES.lproj/Menu.strings
gl-ES.lproj/Panel.strings
gl-ES.lproj/readme.md

Translate to Galician

---

pt-PT.lproj/Front.strings
pt-PT.lproj/Menu.strings
pt-PT.lproj/Panel.strings

Adds European Portuguese translation based on the Brazilian Portuguese translation by aride.moulin@gmail.com
Closes #92

Add european portuguese translation

---

ja-JP.lproj/Menu.strings

Japanese implementation of Menu.strings

add Japanese menu

---

cs-CZ.lproj/Front.strings
cs-CZ.lproj/Menu.strings
cs-CZ.lproj/Panel.strings

Translations extended with a new strings.

Added new translations for Czech

---

id-ID.lproj/Front.strings
id-ID.lproj/Menu.strings
id-ID.lproj/Panel.strings

Hi Typora, as mentioned in the issue page, I made the Indonesian translation to your application. Your review is welcome.

Add Indonesian translation

---

zh-Hans.lproj/Front.strings
zh-Hans.lproj/Menu.strings
zh-Hans.lproj/Panel.strings

reference to [Chinese Copywriting Guidelines](https://github.com/sparanoid/chinese-copywriting-guidelines)

Fix some minor issues and update zh-Hans translation

---

ja-JP.lproj/Front.strings
ja-JP.lproj/Menu.strings
ja-JP.lproj/Panel.strings

Hello, Typora
- I updated Japanese translations according to Base.lproj.
- I also fixed some translations I think needed to fix.
Reviews are welcome.
\# Thank you for developing a very useful Markdown editor!

Update japanese translation

---

pl-PL.lproj/Front.strings

Parę korekt, wprowadziłem nowe określenia, które wydają mi się lepsze, no i dorzuciłem całą masę nowych wierszy, zupełnie nieruszonych do tej pory.

Poprawki i duże uzupełnienie

---

zh-Hans.lproj/Panel.strings

更改 `是否要移动至 %@? ` 为 `是否要移动 %@?`

change translate error

---

zh-Hans.lproj/Menu.strings

Toggle means Open or Close (打开／关闭), not just Open (打开). In Chinese software, "开发者工具" means "打开／关闭开发者工具".

Fix 'Toggle'

---

zh-Hant.lproj/Front.strings
zh-Hant.lproj/Menu.strings
zh-Hant.lproj/Panel.strings

This PR improves the current translation and fills in the missing translation. Most of the improvement is referenced to [Menu items on macOS](https://github.com/martnst/localize-mainmenu) and [Terminology for Windows](https://www.microsoft.com/en-us/language/).

Improve zh-Hant translation

---

pl-PL.lproj/Front.strings
pl-PL.lproj/Menu.strings
pl-PL.lproj/Panel.strings

Front and Menu revised, some small corrections and my email added. Panel revised heavily with lots of new strings translated.

All files revised #2

---

ko-KR.lproj/Menu.strings

1. "Insert Image" Translation.
2. Change three dots to 'HORIZONTAL ELLIPSIS' (U+2026).

Update Menu.strings [ko_KR]

---

pl-PL.lproj/Front.strings
pl-PL.lproj/Menu.strings
pl-PL.lproj/Panel.strings

new strings translated, some old edited, my email address changed

Polish locale updated

---

pl-PL.lproj/Menu.strings

Four new strings translated

---

da-DK.lproj/Front.strings
da-DK.lproj/Menu.strings
da-DK.lproj/Panel.strings

Here's the promised Danish translation of Typora.  It went much faster than anticipated :-)

Added Danish translation of Typora.

---

uk-UA.lproj/Front.strings
uk-UA.lproj/Menu.strings
uk-UA.lproj/Panel.strings

With common OS X menu strings.

Ukrainian translation

---

zh-Hant.lproj/Front.strings
zh-Hant.lproj/Menu.strings
zh-Hant.lproj/Panel.strings

The original translations is perfect enough and I just make some tweaks for translations :smile_cat:

l10n(zh_TW): tweak translations

---

da-DK.lproj/Menu.strings
da-DK.lproj/Panel.strings

Hi guys,
I finally found some time to download and check the newest version of Typora, a version that includes my Danish translation.  I found six errors, which have been fixed in this branch.
Please also add me to the Credits section.
P.S. It appears that the top half of the `Help` menu is hard-coded in Typora?
Cheers,
Archfrog

Fixed six minor translation errors.

---

zh-Hant.lproj/Menu.strings

added translation for `zh-Hant`

---

it-IT.lproj/Front.strings
it-IT.lproj/Menu.strings
it-IT.lproj/Panel.strings

- Added missing strings
- Small fixes to existing entries

Update italian translation

---

fr-FR.lproj/Front.strings
fr-FR.lproj/Menu.strings
fr-FR.lproj/Panel.strings

Here is an enhancement on the translation, that were incomplete (and still are, but almost complete).
Being french, I have updated the translation as I felt they should be. I didn't have the time to finish fr-FR/Panel, I'll finish it later on if nobody wish to finish it.

Updating french translation (fr-FR/Panel incomplete)

---

da-DK.lproj/Front.strings
da-DK.lproj/Menu.strings
da-DK.lproj/Panel.strings

I got a mail from Toke Riis Ebbesen (a fellow Dane) who had spotted a bunch of inconsistencies in the Danish translation.  I've added all his proposed changes and always welcome suggestions.

More fixes of the Danish translation :-)

---

pl-PL.lproj/Panel.strings

enabled in SP > disabled in SP

Line #30 changed

---

pt-BR.lproj/Front.strings
pt-BR.lproj/Menu.strings
pt-BR.lproj/Panel.strings

Many translated strings are now capitalized properly when compared to the original ones. Furthermore, many improvements were made in order to have a more consistent version in Brazilian Portuguese.

Improve strings in Brazilian Portuguese

---

Readme.md
pt-BR.lproj/Front.strings
pt-BR.lproj/Menu.strings
pt-BR.lproj/Panel.strings

The Brazilian Portuguese version is now fully translated and up to date when compared to the base one. Furthermore, a few improvements were made to existing strings.

Add new strings and improve existing ones in Brazilian Portuguese

---

fr-FR.lproj/Menu.strings

Corrected French for "Open" : ~~Ouvirir~~ to Ouvrir.

Correction

---

da-DK.lproj/Front.strings
da-DK.lproj/Menu.strings
da-DK.lproj/Panel.strings

Discovered that a bunch of strings where missing, I've copied them over from Base.* and translated them while at it.

Added and translated recent, missing strings.

---

gl-ES.lproj/Panel.strings

More updates

---

gl-ES.lproj/Menu.strings

Updates an little changes to improve tranlation

Updates an little changes

---

tr-TR.lproj/Panel.strings

Changed word "Discard" to "Yoksay" which is more reliable equivalent than "İptal"

fixed tr_TR translation in panel

---

Readme.md
he-IL.lproj/Front.strings
he-IL.lproj/Menu.strings
he-IL.lproj/Panel.strings

Added Hebrew translation

---

ca-ES.lproj/Front.strings

Updated Catalan translation, correcting some mistakes and typos and polishing style issues.

Updated Catalan translation

---

ca-ES.lproj/Panel.strings

Update Catalan translation fixing typos and giving consistency to all files.

Update Catalan translation

---

pt-BR.lproj/Menu.strings

Update Brazilian translation

---

hu-HU.lproj/Front.strings
hu-HU.lproj/Menu.strings
hu-HU.lproj/Panel.strings

Improved consistency of translation (use the same expressions everywhere).

Translated new strings.

---

it-IT.lproj/Front.strings
it-IT.lproj/Menu.strings
it-IT.lproj/Panel.strings

- Updated translation
- Added missing strings
- Removed strings not present in Base.lproj but only present in it-IT.lproj

Updated Italian translation and added missing strings - it-IT

---

nl-NL.lproj/Front.strings
nl-NL.lproj/Menu.strings
nl-NL.lproj/Panel.strings

Hi!
Thanks for this great application! I have used it with pleasure, though I didn't always find the Dutch translations very accurate or grammatically correct. I therefore went through them and updated them in this PR.
Best,
André

Update Dutch translations

---

Readme.md

Hi again,
Just noticed the credit list in the README, I thought I'd add myself, given the work done on #209.
Best,
André

Edit credits

---

Readme.md
vi-VN.lproj/Front.strings
vi-VN.lproj/Menu.strings
vi-VN.lproj/Panel.strings

+ Add new string from Base folder.
+ Update link to my profile on GitHub. Old link does not work anymore.

Update Vietnamese translation

---

da-DK.lproj/Front.strings
da-DK.lproj/Menu.strings
da-DK.lproj/Panel.strings

Updated the past few months changes so that the Danish translation should be in sync once again.,

Added and translated new strings from Base.lproj.

---

Base.lproj/Front.strings
Base.lproj/Panel.strings

docs: fix typo

---

da-DK.lproj/Welcome.strings

Translated all of the strings in the new `Welcome.strings` file into Danish.
I noticed that there are some errors in the original file: `Trail` should be `Trial` and so on.  Just FYI.

Translated Welcome.strings into Danish.

---

ms-MY.lproj/Front.strings
ms-MY.lproj/Menu.strings
ms-MY.lproj/Panel.strings
ms-MY.lproj/Welcome.strings

I would like to contribute translations for Bahasa Melayu (Malay Language) - Malaysia (ms-MY)

Added locale ms-MY for Bahasa Melayu (Malaysia)

---

Base.lproj/Welcome.strings
ca-ES.lproj/Welcome.strings

I've added catalan translations to ca-ES.lproj folder in the Welcome.strings.
While translating I've detected errors in Base.lproj folder (same file Welcome.strings).

Added translations to ca-ES, and corrected littel errors on Base.lproj (Welcome.strings)

---

id-ID.lproj/Welcome.strings

Added translations for Indonesian Welcome.string based on previous translations to make it consistent.

Added translations for Indonesian Welcome.string

---

Readme.md

Related to #252. Sorry for the trouble.

Added Malay translator to credit

---

es-ES.lproj/Front.strings
es-ES.lproj/Menu.strings
es-ES.lproj/Panel.strings
es-ES.lproj/Welcome.strings

Congrats on hitting 1.0, I have been a Typora user for a while now.
I noticed some incorrect and incomplete translations for the Spanish locale.

Adding corrections and missing Spanish translations

---

Readme.md
de-DE.lproj/Welcome.strings

This pull request adds German (de-DE) translations for Welcome.strings.

Create german (de-DE) translations for Welcome.strings

---

ca-ES.lproj/Menu.strings

Added new strings not already translated in Menu.strings in ca-ES

Translated new lines in Menu.strings

---

zh-Hant.lproj/Welcome.strings

modify traditional Chinese translation

modify translation in welcome.string [zh-Hant]

---

id-ID.lproj/Front.strings
id-ID.lproj/Menu.strings
id-ID.lproj/Panel.strings
id-ID.lproj/Welcome.strings

I checked the translation again. If there is an inaccuracy, then I complete it so that the terms become coherent and matched in the Typora interface.
Please look at the book, "Pedoman Umum Ejaan Bahasa Indonesia (PUEBI)" in <https://badanbahasa.kemdikbud.go.id/lamanbahasa/sites/default/files/PUEBI.pdf>. Check it too <https://kbbi.kemdikbud.go.id/> and/or <http://tesaurus.kemdikbud.go.id/>.

Updated Indonesian Translations to Mix and Match of Typora Terms

---

ko-KR.lproj/Menu.strings
ko-KR.lproj/Panel.strings

This patch addes a bunch of new translations in 'Menu' and 'Panel',
based on the new entries from Base/.

Add new Korean translations for Menu and Panel

---

ca-ES.lproj/Menu.strings

Small style fixes and some ortographic corrections.

Catalan: Minor orthographic and style corrections in Menu strings translation

---

ca-ES.lproj/Panel.strings

Minor corrections on style and ortography

Catalan: Minor corrections on style and ortography at Panel strtings translation

---

ca-ES.lproj/Front.strings

Catalan: Fixing typos in Front.strings

---

ca-ES.lproj/Welcome.strings

Minor correction in ortography and style.

Catalan: Minor correction in ortography and style at Welcome strings translation

---

ko-KR.lproj/Menu.strings
ko-KR.lproj/Panel.strings

My first ko translate contribution. 
Did some(~8~) and made first PR. If it works, will do more while I use Typora..

[ko-KR] Add some ko translate

---

id-ID.lproj/Front.strings
id-ID.lproj/Menu.strings
id-ID.lproj/Panel.strings
id-ID.lproj/Welcome.strings

Added some new vocabulary from Base.lproj.

Update Indonesian translation to complete from Base.lproj

---

pt-BR.lproj/Welcome.strings

Update Welcome.strings [pt-BR]

---

de-DE.lproj/Menu.strings

Adding missing translations, as well as removing a line that is not present in the Base-File anymore.

Updating translations for German (de-DE)

---

hi_IN.lproj/Front.strings
hi_IN.lproj/Menu.strings
hi_IN.lproj/Panel.strings
hi_IN.lproj/Welcome.strings

Hey!
I've added hi-IN translations as mentioned in the issue https://github.com/typora/Typora-i18n/issues/283

added hi-IN translations

---

pt-BR.lproj/Front.strings
pt-BR.lproj/Menu.strings
pt-BR.lproj/Panel.strings
pt-BR.lproj/Welcome.strings

Related to #280
Found a few missing strings in the UI, and after searching the Base Translation folder found about 163 strings missing in the pt-BR directory. Also fixed one or two old translated strings, and moved a few lines so they match exactly the files in the Base files.

Added 163 missing strings from base translation to pt-BR.

---

pl-PL.lproj/Panel.strings

May update

---

es-ES.lproj/Welcome.strings

This commit includes fixes to some issues of orthographic words to spanish language.

Right translation to spanish

---

de-CH.lproj/Menu.strings
de-DE.lproj/Menu.strings

I just corrected a small spelling error in the German translation.

Fixed a spelling error in the German translation.

---

sv-SE.lproj/Front.strings
sv-SE.lproj/Panel.strings
sv-SE.lproj/Welcome.strings

i pretty much just translated all of the untranslated strings, as well as modified a few of the existing ones for consistency

finished swedish translation

---

sl-SI.lproj/Front.strings
sl-SI.lproj/Menu.strings
sl-SI.lproj/Panel.strings

Update Front.strings
Update Menu.strings
Update Panel.strings

translation updates

---

ko-KR.lproj/Menu-electron.strings
ko-KR.lproj/Menu.strings
ko-KR.lproj/Panel.strings

Hi, I used Typora few days, and found some not-translated strings.
Wish this contribution would be helpful to korean Typora users ;)

Updated Ko-KR translations

---

zh-Hans.lproj/Panel.strings
zh-Hant.lproj/Front.strings
zh-Hant.lproj/Menu.strings
zh-Hant.lproj/Panel.strings

Update traditional Chinese translation to the latest version

traditional Chinese translation update

---

Readme.md
zh-Hant.lproj/Front.strings
zh-Hant.lproj/Menu.strings
zh-Hant.lproj/Panel.strings
zh-Hant.lproj/Welcome.strings

Use more appropriate translations in Traditional Chinese.

Update Traditional Chinese translation

---

zh-Hans.lproj/Panel.strings

fix zh-Hans typo

---

zh-Hant.lproj/Front.strings
zh-Hant.lproj/Menu.strings
zh-Hant.lproj/Panel.strings
zh-Hant.lproj/Welcome.strings

Updated translations to the latest version, removed outdated strings and fixed some typos.

Update zh-Hant translation

---

vi-VN.lproj/Front.strings

Update Vietnamese translation.

---

zh-Hans.lproj/Menu.strings
zh-Hans.lproj/Welcome.strings

- Website: 网站->官方网站
- Not Now: 不是现在->以后再说

Update zh-Hans translation

---

vi-VN.lproj/Front.strings

I corrected mistranslations and edited capitalizations (for consistency with English emphases) for Front.strings.

Improved Front.strings translations and capitalizations for Vietnamese

---

tools.sh

I created script to translate Typora to Japanese.
This will be useful for everyone so I make this pull request to add it.
Please see #382 for a detail.

Add useful management tool

---

ja-JP.lproj/Front.strings
ja-JP.lproj/Menu.strings
ja-JP.lproj/Panel.strings
ja-JP.lproj/Welcome.strings

Old translations that are no longer in use were removed and new translations were added.
The current translation rate for Japanese in master is 70.69%, and this pull request will improve that to 99.38.

Add the latest Japanese translation

---

Readme.md
ja-JP.lproj/Menu.strings
ja-JP.lproj/Panel.strings
tools.sh

- Add new Japanese translation
Updated percentage to 99.69%
- Add my name to Readme credit
- Fix typo in `tools.sh`
- Fix my ID typo in Readme 
- Fix script clean up

New Japanese translation and minor fix

---

ja-JP.lproj/Panel.strings

translate several strings

---

da-DK.lproj/Front.strings
da-DK.lproj/Menu.strings
da-DK.lproj/Panel.strings
da-DK.lproj/Welcome.strings

Just realized that there were a bunch of new translation strings added the past year or so.
Perhaps you should consider to add a list of language maintainers and then, more or less, automatically notify them by mail when there is an update to the translation strings?
I'll try to regularly check on the Typora translations strings to see if I need to do anything.

Added Danish translations for the past year or so.

---

fr-FR.lproj/Panel.strings

French translation error correction
